#!/bin/bash
## Created by Juan-Pablo Caceres
## Updated for Qt6 compatibility

# Check for Platform
platform='unknown'
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    echo "Building on Linux"
    platform='linux'
elif [[ "$unamestr" == 'Darwin' ]]; then
    echo "Building on Mac OS X"
    platform='macosx'
fi

# Set qmake command name
if [[ $platform == 'linux' ]]; then
    if hash qmake6 2>/dev/null; then
	echo "Using qmake6"
	QCMD=qmake6
    elif hash qmake-qt5 2>/dev/null; then
	echo "Using qmake-qt5"
	QCMD=qmake-qt5
    elif hash qmake-qt4 2>/dev/null; then
	echo "Using qmake-qt4"
	QCMD=qmake-qt4
    elif hash qmake 2>/dev/null; then #in case qt was compiled by user
	echo "Using qmake"
	QCMD=qmake
    fi
    QSPEC=linux-g++
elif [[ $platform == 'macosx' ]]; then
    QCMD=qmake
fi

if [[ -z "$QCMD" ]]; then
    echo "Error: qmake not found."
    exit 1
fi

# Build
mkdir -p release debug
$QCMD jmess.pro
make clean
$QCMD jmess.pro
make release
